platform :ios, '13.0'

target 'FirebaseChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ARSLineProgress'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'MessageKit'
  pod 'FirebaseAuth'

  target 'FirebaseChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseChatUITests' do
    # Pods for testing
  end

end
